### ISSUE TITLE
 no visible @interface for 'AWSPushManager' declares the selector 'setDefaultPlatformARN:'

### ISSUE THREAD

**Issue by EricRen20** [fetch/AWSPushManager#5]
I got this issue which is so weird. the code looks like correct.
Here is code where I got this issue:
# define AWS_SNS_PlATFORM_ARN @"........"

 AWSPushManager *myPushManager=[AWSPushManager defaultPushManager];
    [myPushManager setDefaultPlatformARN: AWS_SNS_PlATFORM_ARN];

**Comment by koenpunt** [comment]
Did you resolve the issue yourself?
